version: '3.8'

services:
  localstack:
    container_name: greencloud_localstack_demo
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - SERVICES=sts,ec2,cloudwatch,ce
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "./volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
