version: "3.8"

services:
  localstack:
    container_name: greencloud-localstack
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Edge Port
      - "127.0.0.1:4571:4571"            # LocalStack legacy ports (optional)
    environment:
      - SERVICES=ec2,sts,ce             # Enabled services
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "./volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
