"use client";

import { useState } from "react";
import Link from "next/link";

export interface RecommendationItem {
  id: string;
  title: string;
  category: string;
  status: string;
  estimatedMonthlySavings: number;
  estimatedGco2eSavings?: number;
  riskScore: number;
  confidence: number;
  evidence: string;
  evidenceHighlight: string;
  recommendedAction: string;
  terraformSnippet?: string;
  resource?: {
    providerResourceId: string;
    resourceType: string;
    region: string;
    instanceType?: string | null;
  };
}

interface OptimizationQueueProps {
  recommendations?: RecommendationItem[];
  onReviewAction?: (recommendationId: string) => void;
}

export function OptimizationQueue({
  recommendations = [],
  onReviewAction,
}: OptimizationQueueProps) {
  const [selectedItem, setSelectedItem] = useState<RecommendationItem | null>(null);

  // Curated, representative cloud optimization actions with simple, realistic cloud terminology
  const sampleRecommendations: RecommendationItem[] = [
    {
      id: "rec-idle-ec2-01",
      title: "Stop Idle Development Server",
      category: "compute",
      status: "ready",
      estimatedMonthlySavings: 52,
      estimatedGco2eSavings: 12400,
      riskScore: 0.08,
      confidence: 0.98,
      evidence: "Server CPU utilization averaged under 1.2% over the last 14 days with zero active user connections outside business hours.",
      evidenceHighlight: "14-day P95 CPU < 2% • Inactive on nights & weekends",
      recommendedAction: "Schedule automatic nightly shutdown or terminate unused test instance.",
      terraformSnippet: `# Terraform change generated by GreenCloud AI
resource "aws_instance" "dev_api" {
  instance_state = "stopped" # Nightly shutdown schedule
}`,
      resource: {
        providerResourceId: "dev-api-gateway-01",
        resourceType: "EC2 Instance (t3.medium)",
        region: "AWS us-east-1 (N. Virginia)",
        instanceType: "t3.medium",
      },
    },
    {
      id: "rec-rightsize-rds-02",
      title: "Rightsize Overprovisioned Database",
      category: "database",
      status: "ready",
      estimatedMonthlySavings: 184,
      estimatedGco2eSavings: 31200,
      riskScore: 0.22,
      confidence: 0.95,
      evidence: "Allocated 8 vCPUs and 32 GB RAM, but peak workload never exceeded 9% CPU and 4 GB RAM over the past 30 days.",
      evidenceHighlight: "Peak RAM usage 18% • Peak CPU 9% over 30 days",
      recommendedAction: "Downsize to a 2 vCPU / 8 GB RAM Graviton instance during scheduled maintenance window.",
      terraformSnippet: `# Terraform change generated by GreenCloud AI
resource "aws_db_instance" "staging_postgres" {
- instance_class = "db.m5.xlarge"  # 8 vCPU, 32GB RAM ($280/mo)
+ instance_class = "db.t4g.medium" # 2 vCPU, 8GB RAM ($96/mo)
}`,
      resource: {
        providerResourceId: "staging-postgres-cluster",
        resourceType: "RDS Database (PostgreSQL)",
        region: "AWS us-west-2 (Oregon)",
        instanceType: "db.m5.xlarge",
      },
    },
    {
      id: "rec-ebs-orphaned-03",
      title: "Delete Orphaned Storage Disk",
      category: "storage",
      status: "ready",
      estimatedMonthlySavings: 40,
      estimatedGco2eSavings: 6100,
      riskScore: 0.05,
      confidence: 0.99,
      evidence: "500 GB gp3 SSD volume was detached from a deleted virtual machine 38 days ago and continues accumulating hourly storage fees.",
      evidenceHighlight: "Detached for 38 days • Zero read/write IOPS recorded",
      recommendedAction: "Create a final safety backup snapshot and delete the abandoned volume.",
      terraformSnippet: `# Safe deletion workflow:
1. GreenCloud AI creates final safety snapshot: snap-04b7c290a1
2. Generates Terraform destroy plan:
- resource "aws_ebs_volume" "orphaned_disk"`,
      resource: {
        providerResourceId: "vol-084a9e2bc1d8",
        resourceType: "EBS SSD Volume (500 GB gp3)",
        region: "AWS eu-west-1 (Ireland)",
        instanceType: "500 GB gp3",
      },
    },
    {
      id: "rec-s3-tiering-04",
      title: "Archive Inactive Object Storage",
      category: "storage",
      status: "ready",
      estimatedMonthlySavings: 126,
      estimatedGco2eSavings: 14800,
      riskScore: 0.10,
      confidence: 0.96,
      evidence: "8.4 TB of application log archives in S3 Standard have had zero read requests in the last 90 days.",
      evidenceHighlight: "8.4 TB unaccessed for >90 days • S3 Standard tier",
      recommendedAction: "Apply an automated S3 Lifecycle rule to transition objects older than 90 days to Glacier Instant Retrieval.",
      terraformSnippet: `# S3 Lifecycle Rule generated by GreenCloud AI
resource "aws_s3_bucket_lifecycle_configuration" "log_tiering" {
  rule {
    id     = "archive-90d-logs"
    status = "Enabled"
    transition {
      days          = 90
      storage_class = "GLACIER_IR" # 70% cheaper storage
    }
  }
}`,
      resource: {
        providerResourceId: "production-raw-logs-archive",
        resourceType: "S3 Bucket (8.4 TB)",
        region: "AWS us-east-1 (N. Virginia)",
        instanceType: "S3 Standard",
      },
    },
  ];

  const getRiskLabel = (score: number) => {
    if (score < 0.15) return { text: "Low Risk (Safe)", bg: "bg-[#E2F5EF]", textCol: "text-[#1F8A70]", border: "border-[#1F8A70]/20" };
    if (score < 0.35) return { text: "Low Risk (Scheduled)", bg: "bg-[#FFF3D6]", textCol: "text-[#9A6B00]", border: "border-[#9A6B00]/20" };
    return { text: "Medium Risk", bg: "bg-[#FDF4DB]", textCol: "text-[#A97A0B]", border: "border-[#A97A0B]/20" };
  };

  const getCategoryBadge = (category: string) => {
    switch (category) {
      case "compute":
        return { label: "Compute", dot: "bg-[#1F8A70]", bg: "bg-[#E2F5EF]", text: "text-[#1F8A70]", icon: "memory" };
      case "database":
        return { label: "Database", dot: "bg-[#9A6B00]", bg: "bg-[#FFF3D6]", text: "text-[#9A6B00]", icon: "database" };
      case "storage":
        return { label: "Storage", dot: "bg-[#6C63B6]", bg: "bg-[#EFEBFC]", text: "text-[#6C63B6]", icon: "hard_drive" };
      default:
        return { label: "Cloud Waste", dot: "bg-[#7C9A6D]", bg: "bg-[#EDF4EA]", text: "text-[#7C9A6D]", icon: "cloud" };
    }
  };

  return (
    <div className="lg:col-span-5 p-5 sm:p-6 bg-[#FAF6E8]/60 flex flex-col justify-between">
      <div>
        {/* Section Header with non-colliding layout */}
        <div className="mb-4">
          <div className="flex items-center justify-between gap-3 mb-1">
            <div className="flex items-center gap-2">
              <span className="text-[15.5px] font-extrabold text-[#2E2B1A] tracking-tight">
                Recommended Optimizations
              </span>
              <span className="text-[10.5px] font-mono font-bold px-2 py-0.5 rounded-full bg-[#E2F5EF] text-[#1F8A70] border border-[#1F8A70]/20 shrink-0">
                {sampleRecommendations.length} Active
              </span>
            </div>
            <span className="text-[11px] font-mono text-[#7C9A6D] font-semibold flex items-center gap-1 shrink-0">
              <span className="w-1.5 h-1.5 rounded-full bg-[#1F8A70]"></span>
              Human Gate
            </span>
          </div>
          <p className="text-[12px] text-[#686450] leading-snug">
            Evidence-grounded actions ranked by financial ROI and carbon impact
          </p>
        </div>

        {/* Scrollable Sub-Cards Feed with Custom Scrollbar */}
        <div className="max-h-[460px] overflow-y-auto pr-1.5 space-y-3.5 custom-scrollbar">
          {sampleRecommendations.map((item) => {
            const risk = getRiskLabel(item.riskScore);
            const cat = getCategoryBadge(item.category);
            const resourceId = item.resource?.providerResourceId || item.id;

            return (
              <div
                key={item.id}
                className="p-4 rounded-[18px] sm:rounded-[20px] bg-[#FFFDF4] hover:bg-[#FFFDF4] border border-[#ECE5CC] hover:border-[#DFD6B5] transition-all shadow-warm-sm group hover:shadow-warm-md"
              >
                {/* Category & Savings Header */}
                <div className="flex items-center justify-between gap-2 mb-2">
                  <div className="flex items-center gap-1.5 flex-wrap">
                    <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-md text-[10.5px] font-bold ${cat.bg} ${cat.text} border border-[#ECE5CC]`}>
                      <span className={`w-1.5 h-1.5 rounded-full ${cat.dot}`}></span>
                      <span>{cat.label}</span>
                    </span>
                    <span className="font-mono text-[10.5px] text-[#686450] bg-[#FAF6E8] border border-[#ECE5CC] px-2 py-0.5 rounded-md font-semibold">
                      {resourceId}
                    </span>
                  </div>
                  <div className="shrink-0">
                    <span className="font-mono text-[13.5px] font-black text-[#9A6B00] bg-[#FFF3D6] px-2.5 py-0.5 rounded-full border border-[#DFD6B5]">
                      +${item.estimatedMonthlySavings}/mo
                    </span>
                  </div>
                </div>

                {/* Title */}
                <h4 className="text-[13.5px] font-bold text-[#2E2B1A] group-hover:text-[#9A6B00] transition-colors mb-1.5">
                  {item.title}
                </h4>

                {/* Description */}
                <p className="text-[12px] text-[#686450] leading-relaxed mb-2.5">
                  {item.evidence}
                </p>

                {/* Telemetry Highlight Strip */}
                <div className="text-[11px] font-mono text-[#686450] flex items-center gap-1.5 mb-3 bg-[#FAF6E8] px-2.5 py-1.5 rounded-lg border border-[#ECE5CC]">
                  <span className="material-symbols-outlined text-[14px] text-[#1F8A70] shrink-0">
                    query_stats
                  </span>
                  <span className="truncate">{item.evidenceHighlight}</span>
                </div>

                {/* Badges & Action Button */}
                <div className="flex items-center justify-between pt-2.5 border-t border-[#ECE5CC] text-[11px] font-mono">
                  <div className="flex items-center gap-1.5 flex-wrap">
                    <span className={`px-2 py-0.5 rounded-full font-semibold border ${risk.bg} ${risk.textCol} ${risk.border}`}>
                      {risk.text}
                    </span>
                    <span className="px-2 py-0.5 rounded-full bg-[#EFEBFC] text-[#6C63B6] border border-[#6C63B6]/20 font-semibold">
                      {(item.confidence * 100).toFixed(0)}% conf.
                    </span>
                  </div>
                  <button
                    type="button"
                    onClick={() => {
                      setSelectedItem(item);
                      if (onReviewAction) onReviewAction(item.id);
                    }}
                    className="inline-flex items-center gap-1 px-3.5 py-1 text-[11.5px] font-bold rounded-full bg-[#FFF76A] hover:bg-[#F5EC50] border border-[#DFD6B5] text-[#2E2B1A] shadow-sm hover:shadow-sunshine-glow transition-all"
                  >
                    <span>Review Action</span>
                    <span className="material-symbols-outlined text-[13px] leading-none">arrow_forward</span>
                  </button>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Real-time Verification Checklist Footer */}
      <div className="mt-3.5 pt-3 border-t border-[#ECE5CC] flex flex-wrap items-center justify-between text-[11px] font-mono text-[#8D8975] gap-2">
        <div className="flex items-center gap-2">
          <span className="w-2 h-2 rounded-full bg-[#1F8A70] animate-pulse"></span>
          <span className="text-[#2E2B1A] font-bold">Verification Checklist:</span>
        </div>
        <div className="flex items-center gap-2 sm:gap-3 flex-wrap">
          <span>Zero Static Credentials</span>
          <span>•</span>
          <span>CloudWatch Validated</span>
          <span>•</span>
          <span>Terraform PR Ready</span>
        </div>
      </div>

      {/* Evidence & Action Review Modal */}
      {selectedItem && (
        <div className="fixed inset-0 z-50 bg-[#2E2B1A]/40 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="bg-[#FFFDF4] border border-[#ECE5CC] rounded-[24px] max-w-lg w-full p-6 sm:p-7 shadow-warm-xl">
            {/* Modal Header */}
            <div className="flex items-center justify-between mb-4 pb-3 border-b border-[#ECE5CC]">
              <div className="flex items-center gap-2">
                <span className="w-3 h-3 rounded-full bg-[#1F8A70]"></span>
                <h4 className="font-bold text-[16px] text-[#2E2B1A]">{selectedItem.title}</h4>
              </div>
              <button
                type="button"
                onClick={() => setSelectedItem(null)}
                className="w-8 h-8 rounded-full hover:bg-[#FBF6E3] flex items-center justify-center text-[#686450]"
                aria-label="Close dialog"
              >
                ✕
              </button>
            </div>

            {/* Modal Content */}
            <div className="space-y-4 text-[13px] text-[#686450] mb-6">
              {/* Resource Pill */}
              <div className="p-3 rounded-xl bg-[#FAF6E8] border border-[#ECE5CC] font-mono text-[12px]">
                <div className="text-[#8D8975] text-[11px] uppercase tracking-wider mb-1">Target Cloud Resource</div>
                <div className="font-bold text-[#2E2B1A]">{selectedItem.resource?.providerResourceId}</div>
                <div className="text-[11px] text-[#686450] mt-0.5">
                  {selectedItem.resource?.resourceType} • {selectedItem.resource?.region}
                </div>
              </div>

              {/* Problem & Evidence */}
              <div>
                <span className="text-[11px] font-bold font-mono text-[#8D8975] uppercase tracking-wider block mb-1">
                  Detected Inefficiency
                </span>
                <p className="text-[#2E2B1A] font-medium leading-relaxed">
                  {selectedItem.evidence}
                </p>
              </div>

              {/* Recommended Action */}
              <div>
                <span className="text-[11px] font-bold font-mono text-[#8D8975] uppercase tracking-wider block mb-1">
                  Recommended Remediation
                </span>
                <p className="text-[#2E2B1A] leading-relaxed">
                  {selectedItem.recommendedAction}
                </p>
              </div>

              {/* Terraform / IaC Snippet */}
              {selectedItem.terraformSnippet && (
                <div>
                  <span className="text-[11px] font-bold font-mono text-[#8D8975] uppercase tracking-wider block mb-1">
                    Auto-Generated Infrastructure as Code (Terraform)
                  </span>
                  <pre className="p-3 rounded-xl bg-[#2E2B1A] text-[#FFFDF4] font-mono text-[11px] overflow-x-auto leading-relaxed">
                    {selectedItem.terraformSnippet}
                  </pre>
                </div>
              )}

              {/* Impact Badges */}
              <div className="grid grid-cols-2 gap-2 text-center pt-2">
                <div className="p-2.5 rounded-xl bg-[#FFF3D6] border border-[#ECE5CC]">
                  <span className="text-[11px] text-[#9A6B00] block font-mono font-medium">Monthly Cost Savings</span>
                  <strong className="text-[17px] text-[#9A6B00] font-mono font-black">+${selectedItem.estimatedMonthlySavings}/mo</strong>
                </div>
                <div className="p-2.5 rounded-xl bg-[#E2F5EF] border border-[#ECE5CC]">
                  <span className="text-[11px] text-[#1F8A70] block font-mono font-medium">Carbon Reduction</span>
                  <strong className="text-[17px] text-[#1F8A70] font-mono font-black">
                    {((selectedItem.estimatedGco2eSavings || 10000) / 1000).toFixed(1)} kgCO₂e/mo
                  </strong>
                </div>
              </div>
            </div>

            {/* Modal Actions */}
            <div className="flex items-center justify-between pt-3 border-t border-[#ECE5CC]">
              <button
                type="button"
                onClick={() => setSelectedItem(null)}
                className="px-4 py-2 rounded-full border border-[#ECE5CC] text-[#686450] text-[13px] font-medium hover:bg-[#FBF6E3]"
              >
                Close
              </button>
              <Link
                href="/onboarding"
                className="px-5 py-2 rounded-full bg-[#FFF76A] hover:bg-[#F5EC50] border border-[#DFD6B5] text-[#2E2B1A] text-[13px] font-bold shadow-sm inline-flex items-center gap-1.5"
              >
                <span>Connect Cloud Account</span>
                <span className="material-symbols-outlined text-[16px] leading-none">arrow_forward</span>
              </Link>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
